# Generated by Django 5.1.2 on 2024-12-09 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Commodityname", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=3, default=1, max_digits=4),
                ),
            ],
            options={
                "db_table": "商品",
            },
        ),
        migrations.CreateModel(
            name="FestivalDiscount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                "db_table": "节日折扣",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_number", models.AutoField(primary_key=True, serialize=False)),
                ("number_of_guests", models.IntegerField()),
                ("room_number", models.IntegerField()),
                ("check_in_date", models.DateTimeField()),
                ("check_out_date", models.DateTimeField()),
                (
                    "order_status",
                    models.IntegerField(
                        choices=[(0, "未完成"), (1, "已完成")], default=0
                    ),
                ),
            ],
            options={
                "db_table": "订单",
            },
        ),
        migrations.CreateModel(
            name="Subbranch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "分店",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "客户"),
                            ("receptionist", "前台"),
                            ("manager", "店长"),
                            ("admin", "管理员"),
                        ],
                        max_length=20,
                    ),
                ),
                ("branch_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "用户",
            },
        ),
        migrations.CreateModel(
            name="PersonInfo",
            fields=[
                (
                    "id_card",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="p1.order"
                    ),
                ),
            ],
            options={
                "db_table": "人员信息",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("id_card", models.CharField(max_length=50)),
                (
                    "sex",
                    models.CharField(choices=[("1", "男"), ("2", "女")], max_length=5),
                ),
                ("position", models.CharField(max_length=50)),
                ("age", models.DecimalField(decimal_places=0, max_digits=3)),
                (
                    "subbranch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="p1.subbranch"
                    ),
                ),
            ],
            options={
                "db_table": "员工信息",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "roomtype",
                    models.CharField(
                        choices=[
                            ("1", "标间"),
                            ("2", "豪华标间"),
                            ("3", "大床"),
                            ("4", "豪华大床"),
                            ("5", "行政"),
                            ("6", "豪华行政"),
                            ("7", "套房"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=3, default=1, max_digits=4),
                ),
                ("area", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_number_of_guest",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "subbranch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="p1.subbranch"
                    ),
                ),
            ],
            options={
                "db_table": "房间",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="booked_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="p1.user"
            ),
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("consumption", models.JSONField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("check_in_time", models.DateTimeField()),
                ("check_out_time", models.DateTimeField()),
                (
                    "number_of_guest",
                    models.DecimalField(decimal_places=0, max_digits=3),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "未支付"), ("paid", "已支付")],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                (
                    "finish_status",
                    models.CharField(
                        choices=[("finish", "已完成"), ("unfinish", "未完成")],
                        default="unfinish",
                        max_length=10,
                    ),
                ),
                (
                    "festivaldiscount",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="p1.festivaldiscount",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="p1.room"
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="p1.user"
                    ),
                ),
            ],
            options={
                "db_table": "账单",
            },
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("order_status__in", [0, 1])), name="订单_状态_check"
            ),
        ),
    ]
