# Generated by Django 5.1.2 on 2024-11-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0004_bill_finish_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': '节日折扣',
            },
        ),
    ]
