# Generated by Django 5.1.2 on 2024-11-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0005_festivaldiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0),
        ),
    ]
