# Generated by Django 5.1.2 on 2024-11-03 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0007_roomusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='festivaldiscount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p1.festivaldiscount'),
        ),
    ]
