# Generated by Django 5.1.2 on 2024-11-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0008_bill_festivaldiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='roomtype',
        ),
        migrations.AddField(
            model_name='bill',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p1.room'),
            preserve_default=False,
        ),
    ]
