# Generated by Django 5.1.2 on 2024-11-04 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0010_room_subbranch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomusage',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='roomusage',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='roomusage',
            name='use_day',
        ),
        migrations.AddField(
            model_name='roomusage',
            name='end_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomusage',
            name='start_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RoomUsageDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p1.room')),
            ],
            options={
                'db_table': '房间占用日期',
                'unique_together': {('room', 'date')},
            },
        ),
    ]
