# Generated by Django 5.1.2 on 2024-12-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("p1", "0011_remove_roomusage_end_time_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roomusagedate",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="roomusagedate",
            name="room",
        ),
        migrations.DeleteModel(
            name="RoomUsage",
        ),
        migrations.DeleteModel(
            name="RoomUsageDate",
        ),
    ]
