# Generated by Django 5.1.2 on 2024-12-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("p1", "0012_alter_roomusagedate_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_occupied",
            field=models.BooleanField(default=False),
        ),
    ]
